# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZhiHuDaily_Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
     pod 'Alamofire', '~> 4.5'
     pod 'SDWebImage'
     pod 'SlideMenuControllerSwift', '~> 4.0'
     pod 'MBProgressHUD'
     pod 'MJRefresh'
     pod 'LLCycleScrollView'
     pod 'Kingfisher'
  # Pods for ZhiHuDaily_Demo

end
